### ISSUE TITLE
data_info generation

### ISSUE THREAD

**Issue by JiChun-Wang** [DecaYale/RNNPose#1]
Thanks for your provided code.
When I run "run_dataformatter.sh" script to generate formated data containing occlusions, there is not a file named "linemod_all_10k_default.info.all" in $PROJ_ROOT/EXPDATA/data_info.
Hope for your help.

**Comment by DecaYale** [comment]
Hi! You could refer to the updated "doc/prepare_data.md" to download the related files. Sorry for the inconvenience.

**Comment by 63445538** [comment]
Hi, the data_info folder cannot be unzipped, could you please have a check?

![image](https://user-images.githubusercontent.com/16507095/169494743-88ed2dc0-cf17-4d3c-b106-05717ce7ed5a.png)

Best,
Rui

**Comment by DecaYale** [comment]
What is the size of your downloaded data_info.tar? I can successfully unzip it on a mac. Could you provide more information about your machine and the software you use? Thx.

**Comment by 63445538** [comment]
Around 240.4MB. 
I used bsdtar to extract by command line, and it works. But it cannot be extracted by the system default's unzip software. Maybe you could use common formal like 'tar.gz'.

Best,
Rui

**Comment by DecaYale** [comment]
I have tested that using command "tar -xvf " on a ubuntu machine can successfully unzip the file. But the direct click doesn't work. I will upload a ".zip" file later for convenience. Thanks for your patience.
