### ISSUE TITLE
Boundary Box visualisation

### ISSUE THREAD

**Issue by Gan868611** [DecaYale/RNNPose#12]
hi, can i know is there any implemented function in the repo that can visualize the boundary box of predicted pose/GT pose like this
![image](https://user-images.githubusercontent.com/56477330/183037170-147104e0-0542-47d0-b094-eab8e9f058c3.png)

**Comment by DecaYale** [comment]
Hi, maybe not. We referred to PVNet's code base for this visualization. We may add this visualization part later.
