### ISSUE TITLE
where is fuse_formatted file.

### ISSUE THREAD

**Issue by rsinghpatawat** [DecaYale/RNNPose#13]

**Comment by rsinghpatawat** [comment]
Solved with `bash scripts/run_dataformatter.sh`

**Comment by bushengyousan** [comment]
I'm having the same problem, typing bash scripts/run_dataformatter.sh, but it keeps giving me errors and I can't find the file //EXPDATA/raw_data/orig_renders/cat/94_depth.png.npy. How did you solve it?

**Comment by bushengyousan** [comment]
Under my raw_data data there is only a fuse folder, and in fuse there are only pkl files and png files. I hope I can get your help!
