### ISSUE TITLE
textured.obj does not exit

### ISSUE THREAD

**Issue by cxym-yyn** [DecaYale/RNNPose#15]
Hello

I tried to run evaluation but i got this error: 
AssertionError: '/ivclab/RNNPose/model/../EXPDATA/LM6d_converted/models/cat/textured.obj' dose not exist!

And i checked the files, it seems no such files.
I noticed there is a file named models(it seems like a link file but not folder), I downed the dataset twice

Could you give me some advice?

**Comment by DecaYale** [comment]
Temporarily closed as no similar issues are reported by others.
