### ISSUE TITLE
YCBV config files

### ISSUE THREAD

**Issue by xuliwalker** [DecaYale/RNNPose#17]
Hi, thanks for your great work! I wonder if I want to train and  test the model  on the  YCBV dataset , which config files should I use? Moreover, do the training and testing data of the  YCBV dataset exist in the EXPDATA folder. Thanks!

**Comment by DecaYale** [comment]
The YCBV parts have not been released. But it is not hard to implement this part by yourself. I will consider releasing this part later. Sorry for the inconvenience.
