### ISSUE TITLE
LM6d_converted link is broken

### ISSUE THREAD

**Issue by mqtjean** [DecaYale/RNNPose#22]
Hi, thank you for your work,

The link to the [LM6d_converted](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155139432_link_cuhk_edu_hk/EYFaYrk0kcdBgC6WMtLJqP0B9Ar0_Nff9qhI2Cs95qDbdA?e=yYxexC) is broken do you have a new link ?

**Comment by DecaYale** [comment]
I have updated this link, which has also been pasted below for your reference. Thanks. 
https://mycuhk-my.sharepoint.com/:u:/g/personal/1155139432_link_cuhk_edu_hk/EYFaYrk0kcdBgC6WMtLJqP0B9Ar0_Nff9qhI2Cs95qDbdA

**Comment by mqtjean** [comment]
Thank you for your answer ! It works on Chrome (not on Firefox probably a local problem on my side)
