### ISSUE TITLE
End-to-end implementation

### ISSUE THREAD

**Issue by cviviers** [DecaYale/RNNPose#28]
Hi there. 
Thanks for sharing your work and all the code. I was wondering if you have an end-to-end implementation available? As in from new input image, initial pose estimation and then the refinement model. From what I can deduce, this repo picks up with a set of precomputed poses already available. 

Thanks for any feedback!

**Comment by DecaYale** [comment]
In this CVPR work, we focused on the pose refinement part, we therefore didn't release the part for initial pose estimation. If you are interested in an end-to-end implementation, you could refer to previous works such as PVNet, PoseCNN, etc.   
Recently, we developed a more efficient end-to-end solution, but we still have not released this part as this new paper is still under review. Please stay tuned.

**Comment by cviviers** [comment]
Clear, thanks for the response. Looking forward to the next work!
