### ISSUE TITLE
No module named 'thirdparty.kpconv.lib'

### ISSUE THREAD

**Issue by Gan868611** [DecaYale/RNNPose#3]
hi when i try to run `bash eval.sh` or `bash eval_lmocc.sh` it gives me the no module named error, and i dont see thirdparty.kpconv.lib in this case, could you help me on this? am i missing something?

![image](https://user-images.githubusercontent.com/56477330/171601514-b3b26b0e-cfe6-4bbd-8b64-72a3c5447027.png)

![image](https://user-images.githubusercontent.com/56477330/171601574-67e01f32-44ca-49d1-a273-9306cbe35137.png)

**Comment by DecaYale** [comment]
Hi, have you ever run the commands below? If you have, please drop me a message again. 
```
cd RNNPose/scripts
bash compile_3rdparty.sh
```

**Comment by DecaYale** [comment]
Sorry. I find this directory is ignored by the .gitignore file.  I have corrected it and now everything should be ok. Thanks for your feedback.

**Comment by Gan868611** [comment]
thanks!
