### ISSUE TITLE
Can't find the "$seq"_fw0.5.yml config file

### ISSUE THREAD

**Issue by lyj9494** [DecaYale/RNNPose#5]
In the _train.sh_ and _eval.sh_, the config_path equals to /$PROJECT_ROOT_PATH/config/linemod/"$seq"_fw0.5.yml, but I can't find the config file
![image](https://user-images.githubusercontent.com/91005527/172519354-1856717f-0125-4d22-bb0d-d52ec0d13a2c.png)

**Comment by Gan868611** [comment]
hi i think you can try running `bash /config/linemod/copy.sh` to generate the yml file first

**Comment by lyj9494** [comment]
The problem is solved and thank you so much!
