### ISSUE TITLE
bash compile_3rdparty.sh "error"

### ISSUE THREAD

**Issue by GUECHTOULI** [DecaYale/RNNPose#6]
Hello, I'm trying to run this but I get an error message
cd RNNPose/scripts
bash compile_3rdparty.sh

![image](https://user-images.githubusercontent.com/96265512/172557573-441b1c6d-a3f1-4636-a75e-1b6eb1033d40.png)

someone can tell me what the problem is!
thanks!

**Comment by DecaYale** [comment]
You may need to set the environment variable CUDA_HOME, e.g. /usr/local/cuda/

**Comment by GUECHTOULI** [comment]
thank you  
I have another question please when I do the test: bash scripts/eval.sh 
it gives me this
![image](https://user-images.githubusercontent.com/96265512/173768309-74fa395c-e9ef-4f2f-bdf6-645bcefaf25a.png)
what is the problem, and why CUDA_VISIBLE_DEVICES=0

**Comment by DecaYale** [comment]
I assume you have solved this problem. I will close this issue temporarily. If you still have any problem, please feel free to reopen it.
