### ISSUE TITLE
GPG nvidia key error

### ISSUE THREAD

**Issue by yaxiang98** [DecaYale/RNNPose#8]
I met this error when I run ```sudo docker build -t rnnpose .```:

```
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
The command '/bin/sh -c apt-get update   && apt-get install -y -qq --no-install-recommends     libglvnd0     libgl1     libglx0     libegl1     libxext6     libx11-6   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

I did some search on the internet and found that Nvidia updated their keys, but after I updated the keys as described in these blog:
[https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904/11](https://forums.developer.nvidia.com/t/gpg-error-http-developer-download-nvidia-com-compute-cuda-repos-ubuntu1804-x86-64/212904/11)
[https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/](https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/)

 the same error still exists...

**Comment by DecaYale** [comment]
I have referred to https://github.com/NVIDIA/nvidia-docker/issues/1632 and updated the Dockerfile. You could try again.

**Comment by yaxiang98** [comment]
@DecaYale Thanks for updating the Dockerfile, it solves the problem. I would also like to ask what should I use for ```HOST_VOLUME_YOU_WANT_TO_MAP:DOCKER_VOLUME```

I'm not sure if the dockerfile has created a docker volume or I should create a new one? Currently my docker volumes are as follows after I run '''sudo docker build -t rnnpose .'''

```
DRIVER    VOLUME NAME
local     4d087c0ea67d9e69079a2df7ec2b530384848d48cf785982dfe70eb81f9510e4
local     cvat_cvat_data
local     cvat_cvat_db
local     cvat_cvat_keys
local     cvat_cvat_logs
```
they don't seem to be related to RNNPose...

**Comment by DecaYale** [comment]
The parameter HOST_VOLUME_YOU_WANT_TO_MAP:DOCKER_VOLUME is to define a map from your local directory to the directory in the docker container. For example, "/home/your_user_name:/home/your_user_name" is a good choice if your data is saved in your home directory of the local machine. You could ignore the variable $DISPLAY if you have no visualization need.
