### ISSUE TITLE
A problem about the results.

### ISSUE THREAD

**Issue by pyni** [DecaYale/RNNPose#9]
Hi, Thanks for your wonderful works.
I have tried your codes, but It seems the test result doesn't match with the result in your paper. I just follow all the steps from your webside and the config file is the copy from template_fw0.5.yml. Then I run "bash scripts/eval.sh" and I test two objects (ape and cat). The result is shown as follows:

For ape:
2d projections metric: 0.9857142857142858
ADD metric: 0.780952380952381
ADD2 metric: 0.1380952380952381
ADD5 metric: 0.4219047619047619
5 cm 5 degree metric: 0.9876190476190476
mask ap70: nan
seq_len: 1050

For cat:
ADD metric: 0.9421157684630739
ADD2 metric: 0.2275449101796407
ADD5 metric: 0.6117764471057884
5 cm 5 degree metric: 0.9940119760479041
mask ap70: nan
seq_len: 1002

I cannot find the results in your paper
I don't know why?

**Comment by DecaYale** [comment]
Hi, do you install the environment with the docker file provided? We have tested locally and the results should match or are at least close to those reported in our paper.

**Comment by pyni** [comment]
OK, I install it using miniconda.
I will try docker later.

**Comment by pyni** [comment]
Hi, may I ask another question?
the runtime analysis in table 2 is for one iteration or five iteration? It seems not clear.
Thanks.

**Comment by DecaYale** [comment]
Table 2 provides the runtime of each individual module per forwarding.

**Comment by pyni** [comment]
OK, I test it in my PC with 0.7179 second per image using gpu 1660.

**Comment by Arrebol2020** [comment]
> 

Hi，Did you get the same result with the ape model. For ape, I also get 78.1.

**Comment by Arrebol2020** [comment]
> OK, I install it using miniconda. I will try docker later.

Hi，Did you get the same result with the ape model. For ape, I also get 78.1.

**Comment by ChenC-C** [comment]
> > OK, I install it using miniconda. I will try docker later.好的，我使用 miniconda 安装它。我稍后会尝试 docker。
> 
> Hi，Did you get the same result with the ape model. For ape, I also get 78.1.嗨，你用猿模型得到同样的结果吗？对于猿类，我也得到了 78.1。

你好，我使用作者提供的权重推理出来精度也是这么多，请问有找出来问题在哪里吗？
